name: smash
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    
    # compile
    - make
    - gcc
    - gfortran

    # required dependencies
    - f90wrap
    - numpy>=1.13
    - pandas
    - matplotlib
    - h5py
    - tqdm
    - gdal
    - scipy
    - pyyaml
    - SALib>=1.4.5
    - terminaltables
